version: '3'
services:
  monitor-nginx:
    image: nginx:latest
    restart: always
    container_name: monitor-nginx
    volumes:
      - ./images/nginx:/etc/nginx/conf.d
      - ../monitor:/var/www/app
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - monitor-php
      - monitor-postgres
    ports:
      - "81:81"

  monitor-php:
    build: ./images/php
    restart: always
    container_name: monitor-php
    environment:
      APP_DEBUG: 1
    volumes:
      - ../monitor:/var/www/app
      - ./images/php/custom_php.ini:/usr/local/etc/php/conf.d/custom_php.ini

  monitor-postgres:
    image: postgres:12.2-alpine
    restart: always
    container_name: monitor-postgres
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_monitor
    ports:
      - "5432:5432"

  monitor-redis:
    image: redis
    restart: always
    container_name: monitor-redis
    volumes:
      - ./data/redis/data:/data
    ports:
      - "6379:6379"

  monitor-adminer:
    container_name: monitor-adminer
    image: adminer
    restart: always
    ports:
      - "82:8080"